services:
  postgres:
    image: postgres:15
    container_name: fiapcloudgames-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiapcloudgames
    ports:
      - "5432:5432"