services:
  postgres:
    image: postgres:15
    container_name: fiapcloudgames-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiapcloudgames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    container_name: fiapcloudgames-api
    build:
      context: .
      dockerfile: src/FiapCloudGames.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: