services:
  mongodb:
    image: mongo:6.0
    container_name: fiapcloudgames-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api:
    container_name: fiapcloudgames-api
    build:
      context: .
      dockerfile: src/FiapCloudGames.API/Dockerfile
    environment:
      MONGODB__CONNECTION_STRING: "mongodb://admin:admin123@mongodb:27017"
    depends_on:
      - mongodb

volumes:
  mongodb_data: