name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Build com Docker Compose
        run: docker-compose -f docker-compose.yml build

      # Se quiser rodar testes dentro de um container:
      - name: Rodar testes (opcional)
        run: docker-compose -f docker-compose.yml run --rm app dotnet test
